export const LAYOUTS = {
    "apt": "wgdfbqluoyrsthkjneaixcmpvz,.'/",
    "boo": ",.ucvqfdlyaoesgbntri;x'wzphmkj",
    "soul": "qwldpkmuy;asrtgfneiozxcvjbh,./",
    "niro": "qwudpjfyl;asetghnirozxcvbkm,./",
    "flaw": "flawpzkur/hsoycmtenibj'gvqd.x,",
    "isrt": "yclmkzfu,'isrtgpneaoqvwdjbh/.x",
    "qwpr": "qwprfyukl;asdtghnioezxcvbjm,./",
    "zwou": "pldfkzwou,nrthyvsaeiqjmcgxb';.",
    "snug": "qldmbyfou'srtcgpneiazxkwvjh/,.",
    "pine": "ylrdwjmou,csntgphaeixzqvkbf'/.",
    "sind": "y,hwfqkouxsindcvtaerj.lpbgm;/z",
    "aptx": "qcdwxzpou;rstnvyheialgbmjkf',.",
    "arts": "qldygjmou;artscpneihzxkwvbf',.",
    "real": "yluo.zfhcwirea,dtnsm;j'qxpkbgv",
    "rtna": "xdh.qbfoujrtna;gweislkm,/pczyv",
    "xpert": "xpertyuiojqsdfnhaelkzwcvbgm,./",
    "nerts": "pldvxzkou;nrtsgyheiaqjmcwbf',.",
    "rolll": "youwbxkclviaenpdhsrtj/,.qfmg'z",
    "kaehi": "qwldgjuop/nrstmkaehizxcvbyf,.;",
    "heart": "qcdvkjyou;rsthlpnaiewgbmxzf,./",
    "crest": "wlfdkzjuoycrstgpneai'xvmqbh,.;",
    "siuol": "xclgkqjuoyrsthdbneai'wvmzpf.,;",
    "tahan": "tahzyxuiopqvgrsnkblwmfecdj';/-",
    "octa8": "youkxgwdl,iaenfbstrcq/zh'vpmj.",
    "whorf": "flhdmvwou,srntkgyaeixjbzqpc';.",
    "qwerf": "qwerfjylk;asdtghuiopzxcvbnm,./",
    "dwarf": "flhdvzgou.srntmpyeiaxjbkqcw',;",
    "nerps": "xldpvzkou;nrtsgyheiaqjmcwbf',.",
    "dvarf": "'uowpqvdrfaieyglhtns,.;cjkmbxz",
    "asset": "qwjfgypul;asetdhniorzxcvbkm,./",
    "three": "qfuyzxkcwboheaidrtns,m.j;glpv'",
    "fnerb": "twgsbqlnayrhjkdupeoixfmzcv',./",
    "qgmlwy": "qgmlwyfub;dstnriaeohzxcvjkp,./",
    "colman": "qlrwbjmuy;anhsfpteiozxvckgd,./",
    "doerak": "juo'qzvrshgaiexbtndlc.,y;pmfkw",
    "halmak": "wlrbz;qudjshnt,.aeoifmvc/gpxky",
    "trendy": "klhwzjfou,trndcysaeiqxmpbgv.';",
    "whorf6": "vlhkjgwou.srntmydeaixqbfzpc',;",
    "norman": "qwdfkjurl;asetgyniohzxcvbpm,./",
    "dvorak": "',.pyfgcrlaoeuidhtns;qjkxbmwvz",
    "tnwmlc": "tnwmlcbprhsgxjfkqzv;eadioyu,./",
    "qwerty": "qwertyuiopasdfghjkl;zxcvbnm,./",
    "wreath": "jgdfbqluoynsthkwreaixcmpvz,.'/",
    "canary": "wlypbzfou'crstgmneiaqjvdkxh/,.",
    "sturdy": "vmlcpqfoujstrdy.naeizkxgwbh';,",
    "radish": "vcwfqzpuoyrdshlkteaixjmn;bg',.",
    "foalmak": "bx,wvz/utkfoalsneighp'.mcqjydr",
    "semimak": "flhvzqwuoysrntkcdeaix'bmjpg,./",
    "mtgap30": "ypoujkdlcwinea,mhtsrqz/.;bfgvx",
    "colemak": "qwfpgjluy;arstdhneiozxcvbkm,./",
    "workman": "qdrwbjfup;ashtgyneoizxmcvkl,./",
    "megamak": "xlcwkzfuo;yrstmbneaiqjgdvph',.",
    "colemaq": ";wfpbjluyqarstgmneiozxcdkvh/.,",
    "wreathy": "qgdfvjluo,nsthywreaibcmpkzx/'.",
    "calemog": "xlcwkzfuy;orstmbneiaqjvdgph',.",
    "trendei": "klhwbzfou;trndcyseiaqjmgpxv',.",
    "sertain": "xldkvzwou;srtnfgyeiaqjmhbpc',.",
    "rollmak": "qwfpbzluo;crstgmneaivxydkjh/,.",
    "klausler": "k,uypwlmfcoaeidrnthsq.';zxvgbj",
    "whorfmax": "flhykqwou,srntpcdaeixjbvzmg';.",
    "beakl-49": "zyoukgmlpjhieafdstnr/.,'xwcvbq",
    "capewell": ".ywdfjpluqaersgbtnioxzcv;kmh,'",
    "beakl-19": "q.oujwdnm,haeikgsrtpz'/yxbclfv",
    "vitrimak": "tkvumiajbrwx/fpdgq,sh.'colnzye",
    "typehack": "jghpfqvou;rsntkyiaelzwmdbc,'.x",
    "arensito": "ql.p';fudkarenbgsitozw,hjvcymx",
    "beakl-15": "qhouxgcrfzyiea.dstnbj/,k'wmlpv",
    "hands up": "fyou,kwclphiea.dtsrnbj'z;vmgxq",
    "colemaq-f": ";wgpbjluyqarstfmneiozxcdkvh/.,",
    "ctgap 4.0": "xclmkjyou/rsthbpneiaqgwdvzf',.",
    "hyperroll": "pclmvxuoyfnsrtd.aeihbg'wz/,qjk",
    "turducken": "yluvkjwob,iretgfsanhzx;dpmcq./",
    "ctgap 2.0": "wcldkjyou/rsthmpneiaqvgfbzx',.",
    "seht-drai": "fulvb;gnojsehtkqdraiz'mpwycx/,",
    "ctgap 3.0": "vplcfkuoyjrntsd'aeihzbmgwx,.;q",
    "colemak dh": "qwfpbjluy;arstgmneiozxcdvkh,./",
    "minimak-12": "qwdfkyuil;astrghneopzxcvbjm,./",
    "semimak jq": "flhvz'wuoysrntkcdeaixjbmqpg,./",
    "colemak qi": "qlwmkjfuy'arstgpneiozxcdvbh,./",
    "oneproduct": "pldwgjxoyqnrstmuaeihzcfvb,.?;k",
    "semimak jqc": "flhvz'wuoysrntkgdeaixjbmqpc,./",
    "hands right": "vlcdkz'uoynrstgpheaiqxwmjbf,.;",
    "colemak dhv": "qwcpbjluy;arstgmneiozxfdkvh/.,",
    "beakl-19-bis": "qyouzwdnckhiea,gtrspj'/.xvmlfb",
    "colemak qi;x": ";lcmkjfuyqarstgpneiozxwdvbh/.,",
    "colemak qiou": "qlcmkjfoy'arstgpneiuzxwdvbh,./",
    "thumbs right": "xlcgkz'uoynrstdbheaiqwvmjpf.,;",
    "rsi-terminated": "zcywkxlu,qrsitgmneaojfpdbvh'.?",
    "whorfmax ortho": "flhyzqwou,srntpcdaeixjbvkmg';.",
    "vitrimak ortho": "e.viacoqytsj/dgmpx,wrk'lnfuzbh",
    "capewell-dvorak": "',.pyqfgrkoaeiudhtnszxcvjlmwb;",
    "hands down reference": "qchpvkyoj/rsntgwueiaxmldbzf',."
}