export const LAYOUTS = {
    "io": ",.putslg';xwmnohadbqzvfyeircjk",
    "boo": ",.ucvqfdlyaoesgbntri;x'wzphmkj",
    "odu": "xlhfwqodujsrncg.ateivzmpb',k;y",
    "cmk": "ypoujkdlcwinea,mhtsrqz'.;bfgvx",
    "fck": "qfckx'wouzrsthdvnailybgp,/m.;je",
    "ntr": "bdlvfqaujzntrgc'oeispkhwm;.,yx",
    "dnb": "qpdgwzmou,rntcyjhaeixbkv  l';.fs",
    "apt": "wgdfbqluoyrsthkjneaixcmpvz,.'/",
    "idk": "blcmkz';,.nrstwjaeihpxgdvquoyf",
    "sur": "'x,bq.fm/ziratgpcnesylodkjwhuv",
    "uwu": "eu'wcsnjvaob/fkhgq.ptyxmlirz,d",
    "rsnt": "qclmbjfou rsntdyheiazwxgvkp   ",
    "niro": "qwudpjfyl;asetghnirozxcvbkm,./",
    "apty": "jgdlqzyou'rsthkpneiaxcbmvwf,./",
    "lrst": "qwcpkjyou'lrstgmneiaxvfdbzh,./",
    "rrll": "xchpbqyou'rsntgjiaelwfmdv/z,.k",
    "soul": "qwldpkmuy;asrtgfneiozxcvjbh,./",
    "ev25": "bgdlxjyou,sctnqfheiavwmz kp'.;r",
    "anrt": "qhldkjcyu anrtbfsieozpmgvxw   ",
    "maya": "bldgqjfou,nrtsvkhaeixmcwzpy'/.",
    "stag": "xlhmjqwou krntbfseiavpdgzyc   ",
    "lamp": "'lmpqzfou;crstwyneihjxgdk/b,.va",
    "tesc": "krngvjpuo/tlhsfyciaeqzbmxwd,.;",
    "ev21": "vxhgkjwou,rsntmpyeiazbldqfc'.;",
    "ouae": "xplmvqoudjsnrcg'aetizbhfw;.,ky",
    "ev12": "wcldgxuoy.rsntpfheiaqzmbv,k'j/",
    "dvim": "zmldf,uoy'rntsgpaeihxbwcv/kj.q",
    "freq": "qldmxjyou rnstfbhaeizpwgvkc   ",
    "hrst": "flwkvzbuoyhrstd.neai'xcmgp,/qj",
    "nore": "qmluwkdypjnorebhaitszxgv'fc,./",
    "hail": "qwymv kou nrstdphailzxcgjbf',.e",
    "ev20": "vyldkxbou/rcntmfseiazphgqjw',.",
    "ev10": "wfldk,uoyprsntg.iehcxjmbv\u21ef-\u21e7/z'aq",
    "mmmm": "vmlpqzx,u;strdyfnaiojkwcgbh'./e",
    "ev23": "wcldgxuoy.rsntbfheiaqzmpv,k'j;",
    "pine": "ylrmkqfou,csntgbhaeijxzwvpd'/.",
    "isrt": "yclmkzfu,'isrtgpneaoqvwdjbh/.x",
    "ev29": "y,ofbjvrkmiaehpgsnut;.'dzwclxq",
    "flow": "vphmzjfou;snrtxyceiabldkqgw',.",
    "saaz": "/vwmkzfuxqasrtgpneoi.cldjbh',y",
    "iron": "klhbvzcou'trnsmpdaieqxjgfwy,.;",
    "nila": "xdlcvqfou,rtnsbyhaeikmgwzjp'/.",
    "cumy": "nlcumy'vhrdgqfbj;zwsiakpo.,xte",
    "ev24": "hkldgjwo,yruntbfseaiqvmpzxc'./",
    "ev19": "wclpvxfou,rsntgyheiajzmbqkd'.;",
    "arts": "qldgvjfuy'artswpneiozxmcbkh;,.",
    "apos": "jclmkzfouqisrtgpnae'ywxdvbh,./",
    "nstd": "bfmcpzlou,nstdyjraeiqvkgwxh';.",
    "ev22": "wplcfqyou-rdtsgxneiajkmbvzh',.",
    "sind": "y,hwfqkouxsindcvtaerj.lpbgm'/z",
    "rhly": "xhdgjqpou rntsfbceiazlmykvw   ",
    "oooo": "wclfkzvou.rsthyxneiajgmdpqb',;",
    "ev13": "ywouzkdlfvisea,ptncrjx'.;bghmq",
    "zwou": "pldfkzwou,nrthyvsaeiqjmcgxb';.",
    "rtna": "xdh.qbfoujrtna;gweislkm,'pczyv",
    "real": "yluo.zfhcwirea,dtnsm;j'qxpkbgv",
    "nnnn": "bldfvzwuo,nrthygseaiqjmpkxc;'.",
    "aest": ".,;irhwgpq'ayesntmvjxoubldcfkz",
    "inar": "ypolzqmufginarxktesc;b.hjvd,w'",
    "aptx": "qcdwxzpou;rstnvyheialgbmjkf',.",
    "lela": "ylwkjzfou.crstvbnaeixmgdqph'/,",
    "qwpr": "qwprfyukl;asdtghnioezxcvbjm,./",
    "ev11": "kwrgv,uoyftpndm.iehsqblcz;-\u21e7j\u21ef'ax",
    "khlc": "khlcv.ybj'tsrnduaieoqzwm;gfp,x",
    "zyou": "vlhfwzyou,srncgktaeixjmpbqd';.",
    "asrt": "qwldpjfuy asrtghneiozxcvbkm   ",
    "ev15": "bxldw-uof'trncg,iesaqzmpv;.\u21efj\u21e7yhk",
    "snug": "qldmbyfou'srtcgpneiazxkwvjh/,.",
    "ev17": "yfouzqmrxwihea.gtnscjk',;vdlbp",
    "ev27": ",uoyfjgrblaiehkdtncs;.'pqxmwvz",
    "lore": "bcgu.jmopqndsiylretazwfx,vh;k'",
    "vlbu": "vlbuaoygdrz;xk',.cqneiwmsjfpht",
    "ev26": "wbldfjyou,rstcgkneiaqxmpvzh'.?",
    "ants": "xpmdf.roy,antsgqheiu/bwcz;ljkv",
    "flaw": "flawpzkur/hsoycmtenibj'gvqd.x,",
    "test": "qmldpzyoj/rcntbwueiaxgh  kf',.sv",
    "synth": "wlgfk/quoycsthbxreaijvmdpzn',.",
    "rsthd": "jcyfkzl,uqrsthdmnaio/vgpbxw.;-e",
    "test2": "vldmg-uoyfsrtcp.aeihqjkwx/,'; bnz",
    "adept": "/wmpqzk,.;rsntgvhaioxcfdbjluy'e",
    "heart": "qcdvkjyou;rsthlpnaiewgbmxzf,./",
    "short": "juofwkbnlzeiacydtrhs;,.g'vpqmx",
    "engel": "qwfpbjluy;crstgmnaio'xvdkzh,./e",
    "dwarf": "flhdvzgou.srntmpyeiaxjbkqcw',;",
    "kaehi": "qwldgjuop/nrstmkaehizxcvbyf,.;",
    "ctgap": "qplcjxfou/rntsgyheiazbmwvkd',.",
    "boner": "xwlgzqbou,sdrtvfneia/cjmkph\u2018y.",
    "rsthp": "-cyfkzlqu;rsthpmnaiojvgdbxw,./e",
    "ursnf": "klcmbqpaj.ursnfgtoiewxyhvzd',;",
    "skrrt": "vyldgqfoujscrtkbnaeixw'mzph.;,",
    "strd1": "vmlcpqzuo,strdyfneaixkjgwbh;'.",
    "wharf": ".uocfqknl,ieaygvthrs;'wpzmdbjx",
    "iaern": ",ouqjkbmcxiaernhdtys.;'lzpfgwv",
    "fnerb": "twgsbqlnayrhjkdupeoixfmzcv',./",
    "aptlf": "qcmpkjyou'rsthbxneiazwgdv-f/,.l",
    "flame": "xpdwgjfou,rntsyqlaeizbkcvmh';.",
    "tests": "xcldkqyou rnhtbpsaeizfmgvjw   ",
    "nerts": "pldvxzkou;nrtsgyheiaqjmcwbf',.",
    "siuol": "xclgkqjuoyrsthdbneai'wvmzpf.,;",
    "freq2": "qldmkjyou rnstfbhaeizpwgvxc   ",
    "iron2": "klcmvzjou'trshypnaieqxgdfbw.,;",
    "radon": "frlgkqyou'snhtbcdaiezxmpvjw,.;",
    "three": "qfuyzxkcwboheaidrtns,m.j;glpv'",
    "dvarf": "'uowpqvdrfaieyglhtns,.;cjkmbxz",
    "qwerf": "qwerfjylk;asdtghuiopzxcvbnm,./",
    "temma": "zxmbq.fou'srntgpcaeivlhdkjw,/y",
    "tahan": "tahzyxuiopqvgrsnkblwmfecdj';/-",
    "(p_q)": "hsi.,;qplyrtekxfzocbndavj'wgmu",
    "nitro": "pmlcvxfou.ntrsybhaeiqzjgwkd';,",
    "strd2": "vmlcpqzuo,strdyfneaixkjgwbh;/.'",
    "snort": "xplkq'woujsnrtmycaeizbhdvgf.;,",
    "crest": "wlfdkzjuoycrstgpneai'xvmqbh,.;",
    "artsy": "qwdcgjlu,'artsyvneoizxpfbkm/.;h",
    "rolll": "youwbxkclviaenpdhsrtj/,.qfmg'z",
    "crstm": "wlgdvbhuoycrstmfneai'jxkqzp/,.",
    "freq3": "jldmkqyou rnstfbhaeixpwgvzc   ",
    "aujus": ".oujpvglbziaetwyshnr,/;dkfcmxq",
    "ridge": "vmlwqzxou,strdgfnaeikjpc bh';.y",
    "fiend": "wlypb;mou'crstgqneifxjvdkzh,./a",
    "apt30": "vgdfbwluoyrsthkjneaixcmpqz,.'/",
    "learn": ",ourjkpmcxiaenldhtys.;'qzbfgwv",
    "aptv4": "wgdlvjyou'rsthkpneiaxcbmqzf,./",
    "runts": "xpdwgqfou,rntsyjlaeizbkcvmh';.",
    "straw": "xcdmqjyou,nstrwphaeizbglvkf';.",
    "ocmak": ",wfpbxvuy'arstgmneiozcdkqlhj./",
    "aptly": "xcmykjpou'rsthvbneiazwgdq-f/,.l",
    "octa8": "youkxgwdl,iaenfbstrcq/zh'vpmj.",
    "(-_-)": ";oe.lbkpfmiaqnx,htsgzju'rvywcd",
    "asset": "qwjfgypul;asetdhniorzxcvbkm,./",
    "aptex": "/wgdbjfou;rsthvynailxcmkqzp',.e",
    "dhorf": "vlhgqjfou,srntbycaeizxmdkpw';.",
    "csrtk": "'blmzqfuy;csrtkpnaiogvwdjxh,./e",
    "nerps": "xldpvzkou;nrtsgyheiaqjmcwbf',.",
    "apthd": "wfypbqlou'rsthkjneiaxcgdvzm/,.",
    "trash": "vlocx'fpuytrasgkdneiqj.wzhmb,/",
    "whorf": "flhdmvwou,srntkgyaeixjbzqpc';.",
    "(0_0)": "okjyprvdgaq.mfbhzic',ulswxnte;",
    "rsntbj": "xclkvqfou rsntgyheiazwmdbjp   ",
    "dofauq": ".auqmvgphxioetdysnlr,/;wkfcbjz",
    "curtsy": "gldvxjpou crtsybnaiewqmfz/,'. kh",
    "qwertz": "qwertzuiopasdfghjkl;yxcvbnm,./",
    "norman": "qwdfkjurl;asetgyniohzxcvbpm,./",
    "draise": "clmhb'oyg,drtnpxaisuwjkf  .qzve",
    "wogcat": "xie'.zvlybwogcatdrsnu;j,qmkhfp",
    "banana": "qmlbj/fuy'rntscpheioxzvgwkd;,.a",
    "aptmak": "vwfpbjluy'rsthkxnaio;cgdqzm,./e",
    "gemini": "xlmgwqfou,srtdybnaeivjkczph';.",
    "awertz": "awertzuiopqsdfghjklmyxcvbn,./;",
    "testss": "xhldkqwou snrtbfyaeizpmgvjc   ",
    "whaarf": "flhkz'wuq/srntmyceioxjbdvpg;,.a",
    "rusnet": "jylmqwfou.rsntkbceiazxhdvgp',;",
    "spruce": "xdlcbjpou,rtnswyhaeizqmgvkf';.",
    "dvorak": "',.pyfgcrlaoeuidhtns;qjkxbmwvz",
    "nordac": "bcmpkqwou\u00f6nsthdjraeixgvyf.zl\u00e4\u00e5",
    "helium": "pldcgvuoyqnrtsbfheiajxmwzk.';,",
    "ctgapl": "qpmfvjyou'rntswkheiaxbgcz-d/,.l",
    "doerak": "juo'qzvrshgaiexbtndlc.,y;pmfkw",
    "jrstai": "jrstbzgmdiqwypeufca'kvlnxho/,.",
    "whorf6": "vlhkjgwou.srntmydeaixqbfzpc',;",
    "fijiki": "xbwdgqluoyrnstj.heaizpfmvk,/'!c",
    "sturde": "vmlcp;xo,/strdyfnaiuqkjwgbh'.ze",
    "ev13.1": "yfouzkdlmvisea.ptncrjx',;bwhgq",
    "stormy": "zkhgwbfoujstrmy,naeixdlcvqp';.",
    "qgmlwy": "qgmlwyfub;dstnriaeohzxcvjkp,./",
    "radish": "vcwfqzpuoyrdshlkteaixjmn;bg',.",
    "julius": "vcwfkjlu,;nsthy'riaombgdpzx/.qe",
    "dofgun": "ltaxz'weh.rdofvygunijkqmspc;b,",
    "colman": "qlrwbjmuy;anhsfpteiozxvckgd,./",
    "noctum": "bcdmzjfou,nstrvyhaeiqwglxkp';.",
    "rsntvk": "xclbjqfou rsntgyheiazwmdvkp   ",
    "aptlwf": "xcmykjwou'rsthvbneiazfgdq-p/,.l",
    "aptsym": "wcdl,.youqrsthkpneiavbgm'/fjxz",
    "zyvern": "xdlwvqpuoyrthscbneai/kmgjzf'.,",
    "dvimak": "zwmgxpduoynrtscfheai/lkjvqb,.;",
    "aptex2": "/wgdbqyou;rsthkjnailxcmpvzf',.e",
    "trashy": "vlcpkbfou trshymnaiejxgdqzw,. '",
    "querty": "quertywiopasdfghjkl;zxcvbnm,./",
    "nickel": "fmwcvqlouystrdpzhaei kxgbj',;.n",
    "sturda": "vmlcpzxu,'strdyfneioqkjwgbh;./a",
    "crstm2": "pwfmbjluoycrstkxneai'vgdqzh/,.",
    "qwetry": "qwetryuiopasdfghjkl;zxcvbnm,./",
    "canary": "wlypkzxou;crstbfneiajvdgqmh/,.",
    "ev10.1": "wpldk.uoyfrcntv,iehsxgmbz-;\u21e7j/'aq",
    "iaern2": ",ouqjfpmcxiaerndhtys.;'lzbkgwv",
    "ev13.2": "ywouzkdlmvisea.ptncrjx',;bfhgq",
    "sturdy": "vmlcpxfoujstrdy.naeizkqgwbh';,",
    "qwerty": "qwertyuiopasdfghjkl;zxcvbnm,./",
    "jcuken": "jcukengzh-fywaproldvq.smitxb',",
    "osmium": "tb'umdiqwnsv;f,cpx.oekjgyrlzha",
    "whorf2": "flndmvwou,srhtqgyaeijbkxzpc';.",
    "potato": "qlcgvjfou,nrstdyhaeizxwmbkp'/.",
    "tnwmlc": "tnwmlcbprhsgxjfkqzv;eadioyu,./",
    "apthd3": "qcypbjluo;rsthdmneaizfgkvxw,./'",
    "whorse": "vphmqjfou,snrtkycaeixbldzwg';.",
    "dnb-ev": "bxdgw-uof'nrtcy,iesaqzkpv;.\u21efj\u21e7lhm",
    "trendy": "klhwzjfou,trndcysaeiqxmpbgv.';",
    "finary": "wlypb'zou;crstgmneiaxjvdkqh,./f",
    "wreath": "jgdfbqluoynsthkwreaixcmpvz,.'/",
    "azerty": "azertyuiopqsdfghjklmwxcvbn,./;",
    "short2": "juofwqklnvieacymtrhs,;.p'gdxbz",
    "crusty": "wlfpb;mou'crstgqneiaxjvdkzh,./y",
    "halmak": "wlrbz;qudjshnt,.aeoifmvc/gpxky",
    "wourst": "vlngfjbqy/urstdhieaowxmczkp',.",
    "apthd2": "qfypbjluo,rsthkwneaizcgdvxm/'.",
    "castra": "bpdlkqwuoycstr,.neaivgfh';mzxj",
    "em0gus": "vkrcpjfou.stndyqlaeizbxgwmh';,",
    "rollla": "youb.xkclviaen,mhsrt'/pwzfdgjq",
    "scythe": "vcdjxqwou,sytrlfnaeizgkhmbp';.",
    "dofsmi": "rtahqvgnujldofycsmie.k'pzbwx,;",
    "flow-ao": "vphmzjfou,snrtxycaeibldkqgw';.",
    "real-ev": "fwhdg'lu.yscntk\u21e7reoivpmbzxq/;j,a",
    "maks-ex": ";,ud.bfljzaoitgwsnrh/'ypkvcmxqe",
    "testsss": "xlhdkqgou srntbpyaeizjfmvwc   ",
    "ongfsfs": "wvld 'pouyrthcqznaeixkmg/ b,.jfs",
    "nrstmak": "qwypbjkou,nrstdlhaeizxcfgvm';.",
    "roll_in": "wdglq'puoyrtchjzneaixkvm  b;.,fs",
    "natasha": "pmcfkj'uoyntshbwreaiqvgdxzl,.;",
    "apthd30": "vcydbxlou'rsthkwneiajfgpqzm,./",
    "f'ed_up": "wcdl  pouyrsthxznaeivgkm  b.qjf,",
    "megamak": "xlywkzfou;crstgbneiajvdmqph/,.",
    "dvimcat": "wpdgf,.uoyrntsbjheaixvmczkl';q",
    "smiedof": "rtahqvgnujldofycsmie.k'pzbwx,;",
    "semimak": "flhvzqwuoysrntkcdeaix'bmjpg,./",
    "foalmak": "bx,wvz/utkfoalsneighp'.mcqjydr",
    "sertain": "xldkvzwou;srtnfgyeiaqjmhbpc',.",
    "swapsix": "qwdrfyukl;asetghniopzxcvbjm,./",
    "rsntest": "xcldkqfou rsntbpheiazwmgvjy   ",
    "evtest7": "wblcf.ou,xrstdg'aeinqjmpv;-=/zyhk",
    "colemek": "qwfpbjluy'arstgmnhiozxcdvk,./;e",
    "colemaq": ";wfpbjluyqarstgmneiozxcdkvh/.,",
    "colevim": "zwfbp;muy.arstg,neioxvcdqlhjk/",
    "pinerev": "yrlmkqfuo,cnstgbheaijzxwvpd/'.",
    "woagium": "cdlhbpyou,strnmgwaeijkxvzqf';.",
    "phonkie": "qlmpbzfuoyrnthdcseaijxvk;wg'.,",
    "wreathy": "qgdfvjluo,nsthywreaibcmpkzx/'.",
    "stupid2": "qbdlzjfuoyrctswmneai;pkvgxh.',",
    "evtest1": "wcldbkyoj.rsntguheiaqzmpvxf',;",
    "qwertwo": "qwertyblu.asdfmpcnio'z;kjvgh,x",
    "colemap": "qwfgbjluy;arstdhneiozxcpvkm,./",
    "evtest4": "wcldg-uo=yrsntb,ieahqvmpk.;'/jxfz",
    "copemak": "qwfgvjmuy;arstdhneiozxcpbkl,./",
    "crouton": "gldpqzkou,crtnvyhaeiwjmb  x';.fs",
    "ace-vim": "jlhkgqpuo,srntmyceaizxbdvwf/;.",
    "evtest9": "wclpvxfou/rsntgyheiaqzmbjkd',.",
    "therein": "zjoukwplcmsiaedythrn.;vbxgqf?,",
    "calemog": "xlcwkzfuy;orstmbneiaqjvdgph',.",
    "stupid1": "bwdyvxro.uscthfjneaizgmpkql',/",
    "aptsym2": "qckv'/puoyrstlmbneaiwgdh,.fzxj",
    "workman": "qdrwbjfup;ashtgyneoizxmcvkl,./",
    "smeidof": "rtahqvgnujldofycsmie.k'pzbwx,;",
    "stndeez": "vmhcpzlou.stndyqraeij-bgfx/';,kw",
    "evtest3": "wcldg-uo.yrsntb,heaiqvmpkz;/=jxf'",
    "colemak": "qwfpgjluy;arstdhneiozxcvbkm,./",
    "aptmaka": "vwfpbjluy'rsthkxneio;cgdqzm/.,a",
    "mtgap30": "ypoujkdlcwinea,mhtsrqz'.;bfgvx",
    "chiamak": "qvfpj/,.xznrstb'aihcmwgdk-oulye",
    "evtest6": "pwlcf.uoy'nrtdg,iehaqjmbv;-=k/zsx",
    "nitro-s": "pmldxvcou,ntrhybsaeizqjfkwg';.",
    "evtest2": "wgldv.uo-yrsntb,heaiqzmpkx;/=jfc'",
    "pinball": "zkdvqjfou,nthrwysaeipbmlxgc';.",
    "nrst-ex": "xwfpbjluy'nrstgkhaio;vcdqzm,./e",
    "jrstai2": "rwopbyimdasfghjkl'u,qexvctzn/.",
    "stencil": "fdhgwqluoystncbjreaizkmpvx;',.",
    "blutack": "wfldk;uoybcsntp/eaih,vmgxz'.jqr",
    "heartae": "qcdvkjyou;rsthlpneiawgbmxzf,./",
    "trendei": "klhwbzfou;trndcyseiajmgpqxv',.",
    "adept30": "jwmpqzyou'rsntgvheiaxcldbkf,./",
    "rollmak": "qwfpbzluo;crstgmneaivxydkjh/,.",
    "gallium": "bldcvzyou,nrtsgfhaeiqxmwjkp';.",
    "gallaya": "bldczjfou,nrtsgphaeiqxmwvky';.",
    "yrstmak": "qwfpbjlou;yrstkxnaeivcdgzmh'/.",
    "asrt-dh": "qwlmbjfuy asrtgpneiozxcdvkh   ",
    "ctgap-u": "wplcgkdoy'rntsvfheiaxqmbz;/\u21efj-,u.",
    "mayarev": "bldvzqfou,nrtsgyhaeijmcwxkp'/.",
    "ringmak": "fdhmqvwou,stnrzgyaeixkbljpc';.",
    "capewell": ".ywdfjpluqaersgbtnioxzcv;kmh,'",
    "hydrogen": "pmldfwcou,ntrhybsaeizqjkxvg';.",
    "rsntest2": "xcldkqfou rsntbphaeizwmgvjy   ",
    "vitrimak": "tkvumiajbrwx/fpdgq,sh.'colnzye",
    "nstrtest": "pcdlqzwoy,nstrv.ueiabgmhxkf'j;",
    "rsnt-lnm": "xcldkqyou rsntbphaeizwmgvjf   ",
    "whorf-vz": "flhdvzyou,srntmgcaeixjbkqpw';.",
    "asrt-hrl": "qwhgvjpyu asrtbfnieozcldkxm   ",
    "crstemak": "jwfpkxluy'crstbmnaio;vgdqzh,./e",
    "nitrogen": "pmlcwfdou,ntrsgyhaeizqjbvxk';.",
    "mackerel": "qlcgkjfux'arstdyneoizvwmbph/,.",
    "megamak2": "xlcwkzfuo;yrstmbneaiqjgdvph',.",
    "beakl-49": "zyoukgmlpjhieafdstnr/.,'xwcvbq",
    "beakl-19": "q.oujwdnm,haeikgsrtpz'/yxbclfv",
    "aptmak31": "xcfmqbpuy'rstnjkhaio;wglzvd,./e",
    "thallium": "fdhqzjpou,stnrmgcaeivkblxwy';.",
    "ev10.1.1": "wpldk.uoyfrcntv,heisxgmbz-;\u21e7j/'aq",
    "dvorak-e": "',upkqgcljaoihydtsrn;./fxbmwvze",
    "sturdy-m": "juofxpclmviean.ydrts,;'hbwgqkz",
    "frontier": "zmuaqpwhlycsieodtnrfvx;'jbg.,k",
    "real-vim": "wchfzqoulymsntd,aerivgbkp.j'x;",
    "hands-up": "fyou,kwclphiea.dtsrnbj'z;vmgxq",
    "zhenvern": "/kdcfqluoyrthsgxneaiwmpbjzv'.,",
    "rsntests": "qwldzjyou rsntbpheiaxcmgvkf   ",
    "rollymak": "wqfpbjluo,yrstgmneaivxcdkzh/';",
    "zekykern": "zmcpgqluoyrnstbjheaixfwd;kv/.,",
    "whorfmax": "flhykqwou,srntpcdaeixjbvzmg';.",
    "caeserty": "rxfsuzvjpqbteghiklm;aydwcon,./",
    "democrat": "kuiz'qxlpfdemocratnsh;y,.jwgbv",
    "moyaimak": "bldwv'foujnrtsmyhaeizxgcqpk/-;",
    "klausler": "k,uypwlmfcoaeidrnthsq.';zxvgbj",
    "testssss": "qylmzjfou rsntbpheiaxcwgvkd   ",
    "ev10.1.2": "wpldk,uo'yrcntv.heaixgmbq;-=/jfsz",
    "rollmak2": "qwypbjlou'crstgmneiazvfdkxh,./",
    "sturgeon": "vmlypqfou.strdgbnaeizkjcwxh';,",
    "ctgap-ev": "wclbvjfou,rsntgyheiaxzmpqkd'./",
    "aptmak30": ";wfpbqluy'rsthkjnaioxcgdvzm,./e",
    "arensito": "ql.p';fudkarenbgsitozw,hjvcymx",
    "rollmaky": "qwfpbzluo;crstgmneaiyxvdkjh/,.",
    "maks-exd": ";,up.bfljzaoitgwsnrh/'ydkvcmxqe",
    "klawloid": ",gdhnqruoycstfbwjeai.kmpvlz/'x",
    "colevrak": "blfm;'puoqnrstg,heaixwcdvkyz.j",
    "dofsmiee": "rtahqvgnujldofycsmie.k'pzbwx,;",
    "beakl-15": "qhouxgcrfzyiea.dstnbj/,k'wmlpv",
    "typehack": "jghpfqvou;rsntkyiaelzwmdbc,'.x",
    "nstr-sym": "vgdlqzuoybnstr,.aeihpcmw/'kjxf",
    "rsntest1": "qclpkjfou'rsntdyheiazwxbgvm/,.",
    "bubbletea": "qchlwpugz'rsntmyaieojxvd;.fb,k",
    "new_londo": "bmlwfq'pujhnrsc.oteikzxgv,ad;y",
    "maplefyre": "kblmv'cuoytsrn.gdeaiqwzhxfp;,j",
    "nstr-apsu": "pgdljkyou'nstrxvheiabcmwqzf,./",
    "hyperroll": "pclmvxuoyfnsrtd.aeihbg'wz/,qjk",
    "vimtastic": "vmncpq.uo,sthdyjreaixkbgfzlw'/",
    "problem-a": "uojmvrxdk,aephblncty.zifwq;sg'",
    "dofsmieee": "rtahqvgnujldofycsmie.k'pzbwx,;",
    "aptv2-ish": "qcdmxzfou/rstlkyneiawgbhvjp',.",
    "canary-gv": "wlypkzfou'crstbxneiaqjgdvmh,./",
    "stupid1.1": ",uorzkydwbaienjfhtcs;.'lqvpmgx",
    "cmbk-nlhy": "xcmbkqlou rstdwyneiazfgpvjh   ",
    "rsntest2s": "qclmkjfou'rsntdyheiazwxbgvp/,.",
    "beakl-421": "zyou'vglpjhieafdstnrx.,k/wcmbq",
    "sfminimal": "xvhw/qdoy,rsncpgtauizjlfbkm';.e",
    "tailbound": ".lucvkghyqaresfptnio,z;wjbdmx'",
    "turducken": "yluvkjwob,iretgfsanhzx;dpmcq./",
    "nstr-heia": "bgdlqzyou'nstrkjheiapcmwvxf,./",
    "nrst-test": "xlmgwkpaujnrtsyfhoei/qvczbd.;,",
    "sturdyvim": "vmlcpqfouxstrdy.naeizkjgwbh';,",
    "inqwerted": "trewqpoiuygfdsa;lkjhbvcxz/.,mn",
    "ptbr_nrts": "blmvgjpoy/nrtsdfueiazxqcwkh',.",
    "celestial": ",mdpbqluoycstnfjreaiwgkhvxz'.;",
    "ctgap-2.0": "wcldkjyou/rsthmpneiaqvgfbzx',.",
    "demo-crat": "kyl.qwfnuzdemo,scratpjhi'gbx;v",
    "strontium": "wldvjzkou,srtnmycaeiqxghbpf';.",
    "ctgap-4.0": "xclmkjyou/rsthbpneiaqgwdvzf',.",
    "nitrogen2": "mdlcwfpou,ntrsgyhaeizjxbvkq';.",
    "dumbnbass": "wpdgz'muoyrntcjxheaiqbkv  l;.,fs",
    "rollmaky2": "qwfpbzlou;crstgmneiayxvdkjh/,.",
    "ctgap-3.0": "vplcfkuoyjrntsd'aeihzbmgwx,.;q",
    "quick-fox": "thequickbrownfxjmpsvlazydg;,.'",
    "intuition": "bpdl,.wuoycstrqkneaivfgh';mzxj",
    "a-problem": "spgyv;nuqimctkhxz'ejdfw,.lraob",
    "colemaq-f": ";wgpbjluyqarstfmneiozxcdkvh/.,",
    "wouldmain": "would'bqhpmain./ctrskvxf,;ygjze",
    "seht-drai": "fulvb;gnojsehtkqdraiz'mpwycx.,",
    "semiwhorf": "flhdqvwuo,srntkcyeaixjbmzpg;'.",
    "dvorakusp": "/,.pyfgcrlaoeuidhtns;qjkxbmwvz",
    "ruthenium": "wdlfxqbuoyrthsg.neaijkmcvzp',;",
    "solikeuhh": "xcydbzlou'rsthkjneiaqvgfpwm,./",
    "crst-apsu": "wlfpbjmuoycrstkxneai'vgdqzh/,.",
    "republican": "zytdmj,sofrepublicanw;ghk.'vqx",
    "colemak-dh": "qwfpbjluy;arstgmneiozxcdvkh,./",
    "nstr-apsu2": "vgdlqzuoybnstrk,aeihpcmwx/.'jf",
    "radon-test": "fhlgkqyou'snrtbcdaiezmxpvjw,.;",
    "unfinished": "fdhvwqxou.strcymnaeizkjgpbl';,",
    "apt26rstag": "wfgdbjluoyrsthkxneaicmp'qzv,./",
    "aptex-curl": "/wmvqzyou;rsthbpnailxcgdkjf',.e",
    "asrt-hrl-2": "qwhmvjpyu asrtgfnieozcldkxb   ",
    "nerps-shit": "xldpvzkou;nrstgyheiaqjmcwbf',.",
    "colemak-qi": "qlwmkjfuy'arstgpneiozxcdvbh,./",
    "semimak-jq": "flhvz'wuoysrntkcdeaixjbmqpg,./",
    "colemak-kx": "qwfpbjluy'arstgmneiozvcdkxh,./",
    "oneproduct": "pldwgjxoyqnrstmuaeihzcfvb,.';k",
    "trendei-fs": "kvlbw,uoy.trndc-heiaqxmpg\u21e7\u21ef'j/fsz",
    "rollmak-ex": "bwfpkjluy'crstgmnaio/xvdqzh,.;e",
    "canoleymak": "qwfpzjlou'crstkxneiabmgdv-h,./y",
    "trendei-ao": "klhwbzfou,trndcysaeijmgpqxv';.",
    "minimak-12": "qwdfkyuil;astrghneopzxcvbjm,./",
    "2-problems": ";nqxjpctikubozly'd.vehargwfm,s",
    "scelestial": "vmdpbqluoysctnfjreaigwkh/xz;,.",
    "cmbk-nlhy-2": "xcmbkqlou rsthdyneiazwgpfjv   ",
    "corny-furry": "youlqbpmf;iaenxcdtsr,.'v/zgkwjh",
    "hands-right": "vlcdkz'uoynrstgpheaiqxwmjbf,.;",
    "balance-sfb": "q.umkvfhp,oaetwgsrniz'ydjxclb;",
    "nstrpine-ev": "bcdlwjyou.nstrvpheiaxzgmqkf',;",
    "creativemak": "qlcgk/fuy,nrstmpheiozxvwjbd;'.a",
    "wobbyphobia": "wcdp.;fuoyrstnvkleaixgmb,'hzqj",
    "colemak-dhv": "qwcpbjluy;arstgmneiozxfdkvh/.,",
    "engram-apsu": "vwdlqzuoybnsth.,aeicpfmr/'kjxg",
    "nickel_woag": "fmpcvqlou;stndyxhaie kbgwzj.,'r",
    "really_f'ed": "vcwl 'puoyrsthxzneaiqgkm/ b,.jfd",
    "apthd-rstag": "xcydbzlou'rsthkjneiavgfpqwm,./",
    "semimak-jqc": "flhvz'wuoysrntkgdeaixjbmqpc,./",
    "nerves-zxcv": "bldmw'foujnrtsgyhaeizxcvqpk.-/",
    "rollmak-ex2": "qwfpbjluy'crstgmnaio;xvdkzh,./e",
    "crstemak-mv": "jwfpkxluy'crstbvnaiozmgdq;h,./e",
    "cerilious_v4": "clfyvzoubmdrstq.ainhwjgp  ',xke",
    "colemak-pine": "qlcgkjfuy/arstdbneiozxwmvph',.",
    "hwat-is-this": "cvoq;mdulpfseaihtyrngx'.,zkwjb",
    "sertain_edit": "vldkqjfou,srtnbycaeizxmhpgw';.",
    "ace-vim-test": "jlhpgqkuo,srncymteaizxbfwvd/;.",
    "trans-rights": "iougpzdlhvyaec'jtrns/.,wfqkmbx",
    "middlephobia": "wcdl;'puoyrsthxzneaivgfm,.bkqj",
    "thumbs-right": "xlcgkz'uoynrstdbheaiqwvmjpf.,;",
    "rsnt-gy-test": "xclbkqjou rsntvfheiazwmdgyp   ",
    "colemak-qiou": "qlcmkjfoy'arstgpneiuzxwdvbh,./",
    "colemak-qi;x": ";lcmkjfuyqarstgpneiozxwdvbh/.,",
    "colemak-dhgm": "qwcpbzluy'arstkjneiovfdgxmh,./",
    "beakl-19-bis": "qyouzwdnckhiea,gtrspj'/.xvmlfb",
    "beesechurger": "'lucwkgh,jaresfptniozx;yvbdm.q",
    "sturdy_angle": "vmlcpxfoujstrdy.naeikqgwzbh';,",
    "ruthenium_nl": "wdlcxqpou,rtnsgyhaeizkmbvjf';.",
    "alphabetical": "abcdefghijklmnopqrstuvwxyz.,'/",
    "thallium_rlv": "fdhpvqlou,stncymraeijkbgwzx';.",
    "royally_f'ed": "wcvl 'pouyrsthqznaeixgkm/ b,.jfd",
    "amini-layout": "yoxclibfud;p',smgnjeahqtrkzwv.",
    "rsnt-gy-tests": "xclkvqjou rsntbfheiazwmdgyp   ",
    "wobby_sobbing": "gwdpz'luoycrtnqjheaivxkb  m;.,fs",
    "rspace_rollin": "wgdl;zpuoyrcthjqneaixvkm  b',.fs",
    "aptbomination": "qwfpbzluoyrsthkjneaixcgdv;m,.'",
    "bleating_goat": "juoq;kdclwiean'mhstr.,pyxbfgvz",
    "rolls-but-alt": "rxdtgq,oihwncmkuaz;fblsyv'.ejp",
    "roll_in_fixed": "wgdl;zpuoyrcthjqneaixvkm  b',.fs",
    "stronglytyped": "bzlfgjkou,nrtswyheiaxqmcvpd'.;",
    "layoutissimus": "pqmhxy,ojznctsl.uaiekbfrdvgw'/",
    "recycling_bin": "juoq;vdclkiean'mhsrt.,pyxbfgwz",
    "gallaya_angle": "bldcqjfou,nrtsgphaeixmwvzky';.",
    "rsi-terminated": "zcywkxlu,qrsitgmneaojfpdbvh'.?",
    "oxey's-thumb-t": "vblcfz,oy'rsndpkheiaqxmgw.u;j/t",
    "whorfmax-ortho": "flhyzqwou,srntpcdaeixjbvkmg';.",
    "vitrimak-ortho": "e.viacoqytsj/dgmpx,wrk'lnfuzbh",
    "cerilious_v5.1": "clmhpxaygvdrtnb'oisuwjkf  .qz,e",
    "padding-my-list": ".uoyjwfrmxieadkgcnts,;'hqbplvz",
    "whorf_but_based": "vlhdqjwou,srntgycaeizxbmkpf';.",
    "capewell-dvorak": "',.pyqfgrkoaeiudhtnszxcvjlmwb;",
    "deformed-turkey": "qwdpzjluo,rstcymneaixbkgfvh;'.",
    "sturdy_but_good": "vmlfqjcou.strnpydaeizkxhbwg';,",
    "gallium_but_good": "bldwjzpou,nrtsgyhaeixmcvqkf';.",
    "shhh-turn-around": "trndvwfculsh;kzj.,ympiexgq'oab",
    "aptbomination-yx": "qwfdbzluo rsthkjneaixcgpv m,. y",
    "pine-redofstered": "ylrmkqfou,csntwbhaeixzgvjpd'/.",
    "murgle-remastered": "mldfkbpou'nrthvgyeiaqj()xzw-,.sc",
    "thallium_sane(er)": "fdhvqjpou,stnrmgcaeizkblxwy';.",
    "middlephobia_ansi": "wcdlxzpuoyrsth',neaivgfm;.bkqj",
    "middlephobia_angle": "wcdl'zpuoyrsthx,neaigfmv;.bkqj",
    "thallium_alternate": "fdhlqjpou,stnrmycaeivkbxzgw';.",
    "colemak-dhgm-ortho": "qwcpkjluy'arstgmneiozvfdbxh,./",
    "roll_in_fixed_punc2": "wgdlq'puoyrcthjzneaixvkm  b;.,fs",
    "crippling_depression": "yfoujkdclpihea,mtsrnqx'.;bvgwz",
    "hands-down-reference": "qchpvkyoj/rsntgwueiaxmldbzf',.",
    "balance-question-mark": ",uodpfxhjwieagtsynrm.;'qkvzblc",
    "balance-exclamation-mark": "kgcmx'pdy,rnoev.taiszwuljqhfb;",
    "sturdy-index-only-angle-mod": "vmlcpqfoujstrdy.naeixkgwzbh';,",
    "rsi-righthand-strain-injury": "'mxz.tgnolvqfj,sdhaipky;bwcuer",
    "ev's-slightly-modified-nrstmak": "fyrpbjkou,scntdlheiavqxwgzm'.;",
    "whorf-but-with-a-repeat-column": "flhdmvw#uosrntkgy@eixjbzqpc%a.",
    "rolll<:skullcat:974479503097229362>": "youb.xkclviaen,mhsrtz'/pwfdgjq",
    "marxist-leninist-maoist-third-wordist": "zmlfbqodujsnrcg'ateivxhpw.,k;y",
    "laissez-faire-free-market-corporatist": "rqlz;cs.tbmoneyfw,pdjax'uvgikh"
}
